AdminUser.create(email: 'test', password: 'test', club_name: 'Ricers FC');

Player.create(first_name: 'Mac', last_name: 'Daddy', position: 1, price: 67, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Mad', last_name: 'Steve', position: 1, price: 88, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'John', last_name: 'Ward', position: 2, price: 62, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Harry', last_name: 'Painter', position: 2, price: 75, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'James', last_name: 'Sykes', position: 2, price: 86, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Ali', last_name: 'Carroll', position: 2, price: 91, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'James', last_name: 'Kelly', position: 2, price: 54, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Toby', last_name: 'Allitt', position: 2, price: 46, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Mike', last_name: 'Clifford', position: 2, price: 37, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Pat', last_name: 'Sykes', position: 3, price: 69, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Peter', last_name: 'Sampson', position: 3, price: 77, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Alex', last_name: 'Reed', position: 3, price: 80, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Jake', last_name: 'McCausland', position: 3, price: 95, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Dom', last_name: 'Oniell', position: 3, price: 50, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Ant', last_name: 'Lomas', position: 3, price: 47, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Jack', last_name: 'Vincent', position: 3, price: 34, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Andy', last_name: 'Wood', position: 3, price: 81, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Alex', last_name: 'Sampson', position: 4, price: 67, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Goat', last_name: 'Goat', position: 4, price: 72, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Dom', last_name: 'Beckham', position: 4, price: 89, availability: 'a', admin_user_id: 1);
Player.create(first_name: 'Matt', last_name: 'Barber', position: 4, price: 90, availability: 'a', admin_user_id: 1);